name: Point Cloud Evaluation Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  classification:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout datasets repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Checkout ground truth repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.GROUND_TRUTH_REPO }}
          token: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}
          path: ground-truth

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --fix-missing --no-install-recommends \
            libtbb2 \
            libboost-iostreams1.74.0 \
            libboost-system1.74.0 \
            libboost-serialization1.74.0 \
            libpdal-base13 \
            libgomp1 \
            curl \
            jq \
            zip

      - name: Run classification workflow
        run: |
          bash evaluation/run.sh
        env:
          GROUND_TRUTH_REPO_TOKEN: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}

      - name: Comment in PR with results
        run: |
          bash evaluation/comment_stats.sh
        env:
          GROUND_TRUTH_REPO_TOKEN: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}

      - name: Upload model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: new-model
          path: new-model.bin

      - name: Upload stats file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: new-stats
          path: new-stats.zip


  create_release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ground truth repository
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.GROUND_TRUTH_REPO }}
        token: ${{ secrets.GROUND_TRUTH_REPO_TOKEN }}
        path: ground-truth

    - name: Download model artifact
      uses: actions/download-artifact@v3
      with:
        name: new-model

    - name: Download new stats artifact
      uses: actions/download-artifact@v3
      with:
        name: new-stats

    - name: Unzip stats file
      run: unzip new-stats.zip

    - name: Display structure of downloaded files
      run: ls -R

    - name: Replace and push new stats files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        find ground-truth -type f -iname "new-stats.json" -exec bash -c 'mv $0 ${0/new-/}' {} \;
        git add ground-truth
        git commit -m "Replace stats.json with new-stats.json"
        git push origin main

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Description of the release
        draft: false
        prerelease: false

    - name: Upload file to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: new-model.bin
        asset_name: new-model.bin
        asset_content_type: text/plain